site_name: Krypton - ML/DL Model Server
theme:
  name: material
  language: en
site_author: Varun Kruthiventi
nav:
    - 'index.md'
    - 'installation.md'
    - 'adding-models.md'
    - 'accesing-models.md'
    - 'making-predictions.md'
repo_name: saivarunk/krypton
repo_url: https://github.com/saivarunk/krypton
google_analytics:
  - UA-85777603-4
  - auto